Flask-blog/blog/users/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user, login_user
from werkzeug.exceptions import NotFound

# import blog.articles.views
from werkzeug.security import generate_password_hash

from blog.extensions import db
from blog.forms.user import UserRegisterForm
from blog.models import User

user = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@user.route('/')
def users_list():
    users = User.query.all()
    return render_template(
        'users/list.html',
        users=users,
        request=request,
    )


@user.route('/<int:pk>')
@login_required
def profile(pk: int):
    selected_user = User.query.filter_by(id=pk).one_or_none()
    if not selected_user:
        raise NotFound(f"User #{pk} doesn't exist!")

    return render_template(
        'users/profile.html',
        user=selected_user,
    )


@user.route('register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('user.profile', pk=current_user.id))

    form = UserRegisterForm(request.form)
    errors = []
    if request.method == 'POST' and form.validate_on_submit():
        if User.query.filter_by(email=form.email.data).count():
            form.email.errors.append('Email is not unique')
            return render_template('users/register.html', form=form)

        _user = User(
            email=form.email.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            password=generate_password_hash(form.password.data)
        )

        db.session.add(_user)
        db.session.commit()

        login_user(_user)
        return redirect(url_for('user.profile', pk=_user.id))

    return render_template(
        'users/register.html',
        form=form,
        errors=errors,
    )

Flask-blog/blog/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS -->
    {% block css %}
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet"

    {% endblock %}

</head>
<body>
<div class="container">
    {% block header %}
        {% include 'navbar.html' %}
    {% endblock %}
    {% block content %}
    {% endblock %}
    {% block footer %}
    {% endblock %}
</div>
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
{% block js %}
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}">
    </script>
{% endblock %}
<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
-->
</body>
</html>

Flask-blog/blog/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link {{ 'active' if request.endpoint in ['user.users_list','user.profile'] }}"
                       href="{{ url_for('user.users_list') }}">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ 'active' if request.endpoint in ['author.author_list'] }}"
                       href="{{ url_for('author.author_list') }}">Authors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ 'active' if request.endpoint in ['article.articles_list', 'article.get_article', 'article.get_article_by_tag_name'] }}"
                       href="{{ url_for('article.articles_list') }}">Articles</a>
                </li>

                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link {{ 'active' if request.endpoint in ['article.create_article_form'] }}"
                           href="{{ url_for('article.create_article_form') }}">Create article</a>
                    </li>
                    {% if current_user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('admin.index') }}">Admin panel</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout ({{ current_user.email }})</a>
                    </li>
                {% endif %}
                {% if not current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.login') }}"
                           class="nav-link {{ 'active' if request.endpoint == 'auth.login' }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('user.register') }}"
                           class="nav-link {{ 'active' if request.endpoint == 'user.register' }}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>