Flask-blog/blog/forms/article.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators, SubmitField, TextAreaField, SelectMultipleField


class CreateArticleForm(FlaskForm):
    title = StringField('Title', [validators.DataRequired()])
    text = TextAreaField('Text', [validators.DataRequired()])
    tags = SelectMultipleField('Tags', coerce=int)
    submit = SubmitField('Create')

Flask-blog/blog/articles/views.py
from typing import Dict

import requests
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from sqlalchemy.orm import joinedload
from werkzeug.exceptions import NotFound

from blog.extensions import db
from blog.forms.article import CreateArticleForm
from blog.models import Article, Author, Tag

article = Blueprint('article', __name__, url_prefix='/articles', static_folder='../static')


@article.route('/')
def articles_list():
    articles = Article.query.all()
    count_articles: Dict = requests.get('http://127.0.0.1:5000/api/articles/event_get_count/').json()
    return render_template(
        'articles/list.html',
        request=request,
        articles=articles,
        count_articles=count_articles['count'],
    )


@article.route('/create', methods=['GET'])
@login_required
def create_article_form():
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]

    return render_template(
        'articles/create.html',
        form=form,
    )


@article.route('/', methods=['POST'])
@login_required
def create_article():
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]
    errors = []
    if form.validate_on_submit():
        _article = Article(title=form.title.data.strip(), text=form.text.data.strip())

        if current_user.author:
            _article.author_id = current_user.author.id
        else:
            author = Author(user_id=current_user.id)
            db.session.add(author)
            db.session.flush()
            _article.author_id = author.id

        if form.tags.data:
            selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
            for tag in selected_tags:
                _article.tags.append(tag)

        db.session.add(_article)
        db.session.commit()

        return redirect(url_for('article.get_article', article_id=_article.id))

    return render_template(
        'articles/create.html',
        form=form,
        errors=errors,
    )


@article.route('/<int:article_id>', methods=['GET'])
def get_article(article_id: int):
    _article: Article = Article.query.filter_by(
        id=article_id
    ).options(
        joinedload(Article.tags)
    ).one_or_none()
    if _article is None:
        raise NotFound
    return render_template(
        'articles/article.html',
        article=_article,
    )


@article.route('/<string:tag_name>', methods=['GET'])
def get_article_by_tag_name(tag_name: str):
    _tag: Tag = Tag.query.filter_by(name=tag_name).options(joinedload(Tag.articles)).one_or_none()
    if _tag is None:
        raise NotFound
    return render_template(
        'articles/article_by_tag_name.html',
        tag=_tag,
    )

Flask-blog/blog/templates/articles/article.html
{% extends 'base.html' %}

{% block title %}
    {{ article.title }}
{% endblock %}

{% block content %}
    <div class="mt-4">
        <h1>{{ article.title|title }}</h1>
        <p>{{ article.text }}</p>

        <div class="d-flex">
            <div class="col-6">
                <div>Author: <a
                        href="{{ url_for('user.profile', pk=article.author.user.id) }}">{{ article.author.user.first_name }} {{ article.author.user.last_name }}</a>
                    ({{ article.author.id }})
                </div>
                <div>Created at: {{ article.created_at }}</div>
                <div>Updated at: {{ article.updated_at }}</div>
            </div>
            <div class="col-6">
                {% for tag in article.tags %}
                    <span class="badge bg-primary "><a class="text-decoration-none text-white" href="
                            {{ url_for('article.get_article_by_tag_name', tag_name=tag.name) }}">{{ tag.name }}</a></span>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

Flask-blog/blog/templates/articles/article_by_tag_name.html
{% extends 'base.html' %}

{% block title %}
    Articles list
{% endblock %}

{% block content %}
    <h1>Articles: {{ tag.name }}</h1>
    <ul class="mt-3">
        {% for article in tag.articles %}
            <li class="fs-3"><a style="text-decoration: none;"
                    href="{{ url_for('article.get_article', article_id=article.id) }}">{{ article.title|title }}
                ({{ article.author.user.first_name }} {{ article.author.user.last_name }})</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

Flask-blog/blog/templates/articles/create.html
{% extends 'base.html' %}
{% from 'macro/formhelpers.html' import render_field %}

{% block title %}
    Create Article
{% endblock %}

{% block content %}
    {% if errors %}
        {% for error in errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    {% endif %}
    <form method="POST" action="{{ url_for('article.create_article') }}">
        {{ form.csrf_token }}
        {% for field in ['title', 'text', 'tags'] %}
            {{ render_field(form[field]) }}
        {% endfor %}
        {{ form.submit(class="btn btn-primary mb-3") }}
    </form>
{% endblock %}

Flask-blog/blog/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}
    Articles list
{% endblock %}

{% block content %}
    <h1>Articles: Count from RPC call {{ count_articles }}</h1>
    <ul class="mt-3">
        {% for article in articles %}
            <li class="fs-3"><a style="text-decoration: none;"
                    href="{{ url_for('article.get_article', article_id=article.id) }}">{{ article.title|title }}
                ({{ article.author.user.first_name }} {{ article.author.user.last_name }})</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}